export const USER_STATE_CHANGE = 'USER_STATE_CHANGE';
export const SET_GAME_MODE = 'SET_GAME_MODE';
export const CONNECTION_STATUS_CHANGE = 'CONNECTION_STATUS_CHANGE';
export const ROOMS_STATE_CHANGE = 'ROOMS_STATE_CHANGE';
export const SET_BOARD_GAME = 'SETTINGS_BOARD_GAME';
export const SET_SIZE_MARK = 'SET_SIZE_MARK';
export const VOLUME_STATE_CHANGE = 'VOLUME_STATE_CHANGE';
